增加使用案例：增加 VS Code 使用案例，使用插件格式化代码
moonbingbing/openresty-best-practices pull request #317
Opened 2021-01-04 07:28 UTC by Miss-you

2021-01-05 14:45 UTC, membphis requested changes

2021-01-05 14:45 UTC, membphis commented on lua/editor.md
> +#### 使用插件格式化代码
这个并不推荐使用哈

目前 lua 的代码格式化工具，效果都不好

2021-01-07 14:44 UTC, Miss-you commented on lua/editor.md
> +#### 使用插件格式化代码
> 这个并不推荐使用哈
> 
> 目前 lua 的代码格式化工具，效果都不好

确实，没有比较好用的。

但对于初学者来讲，还是需要一个格式化工具的

那我在这里面增加tag，不推荐么？其次说明下，并没有非常好效果的lua格式化工具

2021-01-07 14:47 UTC, Miss-you commented on lua/editor.md
> +#### 使用插件格式化代码
> 这个并不推荐使用哈
> 
> 目前 lua 的代码格式化工具，效果都不好

又跟同事交流了一下，腾讯开源的一个lua-helper插件格式化似乎还不错。我试试

2021-01-11 03:39 UTC, membphis commented on lua/editor.md
> +#### 使用插件格式化代码
there are many `lua helper`
看上去需要个更好的名字

2021-01-11 03:40 UTC, membphis commented on lua/editor.md
> +#### 使用插件格式化代码
https://www.google.com/search?q=lua-helper&oq=lua-helper&aqs=chrome..69i57j0i30j0i8i30j0i8i10i30j0i8i30l2.223j0j1&sourceid=chrome&ie=UTF-8

2021-01-22 06:00 UTC, membphis commented on lua/editor.md
> +代码格式化是一个无聊但又重要的工作，我们通常会使用专门的格式化工具来格式化代码（比如 golang 中的`go fmt`，或者 lua 的`lua-format`工具）。在 VS Code 平台，我们可以使用`Lua Helper` 插件内置的代码格式化工具来格式化 Lua 代码。
加个链接更好

2021-01-29 11:06 UTC, Miss-you commented
luahelper还未开源，仅仅是在vscode放出来插件，背后团队肯定靠谱，是要给整个IEG使用的插件，开源要半年后吧
@membphis

2021-01-29 14:27 UTC, membphis commented
好滴，那就先合并。也听听反馈

2021-01-29 14:27 UTC, merged