将readme章节提取出来，并更新gitbook最新地址
moonbingbing/openresty-best-practices pull request #323
Opened 2021-03-03 17:42 UTC by Miss-you

1. 拆出为什么写作本书章节
2. 更新gitbook最新地址

2021-03-04 10:37 UTC, membphis requested changes
少了最灵魂的“为什么要写这本书”，我认为新版不如之前旧的。
既然这是一本书，那么就应该主要定位“为什么要写”，“希望对谁有益”，“预期效果“等，这是书的核心。

![image](https://user-images.githubusercontent.com/6814606/109951249-6c9f5300-7d18-11eb-9b22-b96435c3ecb1.png)

2021-03-04 10:37 UTC, membphis commented on README.md
> +当前维护者：yousali
不是个人维护的哈，这里不合适

2021-03-04 10:37 UTC, membphis commented on README.md
> +[在 gitbook 上查看本书](https://yousali.me/openresty-best-practices/)
为什么要修改为为个人 gitbook 地址呢？原因是什么？

2021-03-04 10:37 UTC, closed without merging

2021-03-04 10:38 UTC, membphis commented
I suggest you can submit a new PR if you want to change part of e-book.

2021-03-05 02:25 UTC, Miss-you commented
收到，我重新花些时间看看，看看怎么解决

2021-03-05 02:26 UTC, Miss-you commented on README.md
> +[在 gitbook 上查看本书](https://yousali.me/openresty-best-practices/)
> 收到，我重新花些时间看看，看看怎么解决



> I suggest you can submit a new PR if you want to change part of e-book.

收到，我重新花些时间看看，看看怎么解决